# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TweetGram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TweetGram
  pod 'OAuthSwift', '~> 2.0.0'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'Kingfisher', '~> 5.13'

end
